image: maven:3-openjdk-18

stages:
  - test

junit-tests:
  stage: test
  script:
    - mvn verify
  only:
    - merge_requests
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
